
import { LayoutProvider } from "~/useContext/layoutContext";
import { cn } from "~/lib/utils";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en"  >
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
        )}
      >
      <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  )
}
